{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "crypto-app.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crypto-app.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - configmaps
      - namespaces
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]

  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - prometheuses
      - alertmanagers
    verbs: ["get", "list", "watch"]
{{- end }}
