apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default (include "crypto-app.fullname" .) }}
  labels:
    {{- include "crypto-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.httpsTargetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "crypto-app.selectorLabels" . | nindent 4 }}
