{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "crypto-app.fullname" . }}
  labels:
    {{- include "crypto-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "crypto-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scrapeTimeout: 10s
{{- end }}
